services:
  postgres:
    container_name: postgres
    image: postgres:18.1-alpine3.23
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      # - PGDATA=var/lib/postgresql/18/docker
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    # volumes:
    # - ./postgres/pg_data:/var/lib/postgresql/data/18/docker/postgresql.conf
    # - postgres/pg_data/postgresql.conf:/var/lib/postgresql/data/18/docker/postgresql.conf
    # - pg_data:/var/lib/postgresql/data/18/docker/postgresql.conf

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.11.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres

  # ollama:
  #   image: docker.io/ollama/ollama:0.13.5
  #   # environment:
  #   #   - OLLAMA_MODEL=${MODEL_NAME}
  #   #   - OLLAMA_HOST=http://${MODEL_HOST}:${MODEL_PORT}
  #   ports:
  #     - 11434:11434
  #     # - ${MODEL_PORT}:${MODEL_PORT}
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   container_name: ollama
  #   command: serve && ollama run ${MODEL_NAME}



    # pull_policy: always
    # tty: true
    # restart: always
    # environment:
    #   - OLLAMA_KEEP_ALIVE=24h
    #   - OLLAMA_HOST=0.0.0.0
    # networks:
    #   - ollama-docker


# volumes:
#   pg_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./postgres/pg_data