services:
  postgres:
    container_name: postgres
    image: postgres:18.1-alpine3.23
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      # - PGDATA=var/lib/postgresql/18/docker
      - POSTGRES_DB=RLT_videos #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    # volumes:
    # - ./postgres/pg_data:/var/lib/postgresql/data/18/docker/postgresql.conf
    # - postgres/pg_data/postgresql.conf:/var/lib/postgresql/data/18/docker/postgresql.conf
    # - pg_data:/var/lib/postgresql/data/18/docker/postgresql.conf


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.11.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres

# volumes:
#   pg_data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./postgres/pg_data


